Payment.delete_all
OrderItem.delete_all
Order.delete_all
CampaignProduct.delete_all
Campaign.delete_all
Product.delete_all
User.delete_all

puts "DB clean"

user1 = User.create(email: 'filipo@gmail.com', password: '123456', name: 'Filipo', seller: true, nickname: 'Pipo', description: 'One of the best emerging artists in 2021, thanks to his melodic voice and beautiful vocals. His has a wonderful devotion to his fans. He continuosly demonstrates it and we can see this through this merch drop dedicated exclusively to his beloved fans.', address: 'Italy')
photo_user1 = URI.open('https://c4.wallpaperflare.com/wallpaper/643/641/261/singers-kendrick-lamar-wallpaper-preview.jpg')
user1.photo.attach(io: File.open(photo_user1), filename: 'nes.jpg', content_type: 'image/jpg')
user2 = User.create(email: 'carles@gmail.com', password: '123456', name: 'Carles', seller: true, nickname: 'Carls', description: 'One of the best emerging artists in 2021, thanks to his melodic voice and beautiful vocals. His has a wonderful devotion to his fans. He continuosly demonstrates it and we can see this through this merch drop dedicated exclusively to his beloved fans.', address: 'Girona')
photo_user2 = URI.open('https://wallpapercave.com/wp/wp1835627.jpg')
user2.photo.attach(io: File.open(photo_user2), filename: 'nes.jpg', content_type: 'image/jpg')
user3 = User.create(email: 'max@gmail.com', password: '123456', name: 'Max',seller: false, nickname: 'Maxim', description: 'One of the best emerging artists in 2021, thanks to his melodic voice and beautiful vocals. His has a wonderful devotion to his fans. He continuosly demonstrates it and we can see this through this merch drop dedicated exclusively to his beloved fans.', address: 'Belgium')
photo_user3 = URI.open('https://i.pinimg.com/originals/2c/0c/e8/2c0ce826414c964703e12c1ad8e1bd96.png')
user3.photo.attach(io: File.open(photo_user3), filename: 'nes.png', content_type: 'image/png')
user4 = User.create(email: 'alejandro@gmail.com', password: '123456', name: 'Alejandro', seller: false, nickname: 'Mlejandrini', description: 'One of the best emerging artists in 2021, thanks to his melodic voice and beautiful vocals. His has a wonderful devotion to his fans. He continuosly demonstrates it and we can see this through this merch drop dedicated exclusively to his beloved fans.', address: 'Mexico')
photo_user4 = URI.open('https://i.pinimg.com/564x/be/d0/77/bed077aaca3aaab4b167245fec3c322b.jpg')
user4.photo.attach(io: File.open(photo_user4), filename: 'nes.jpg', content_type: 'image/jpg')
user5 = User.create(email: 'kay@gmail.com', password: '123456', name: 'Lil Wayne', seller: true, nickname: 'lilW', description: 'One of the best emerging artists in 2021, thanks to his melodic voice and beautiful vocals. His has a wonderful devotion to his fans. He continuosly demonstrates it and we can see this through this merch drop dedicated exclusively to his beloved fans.', address: 'Italy')
photo_user5 = URI.open('https://images.complex.com/complex/images/c_fill,dpr_auto,f_auto,q_auto,w_1400/fl_lossy,pg_1/ns9m2ehhozxcg2bf3935/lil-wayne-new-orleans-getty-erika-goldring?fimg-ssr-default')
user5.photo.attach(io: File.open(photo_user5), filename: 'nes.jpg', content_type: 'image/jpg')
user6 = User.create(email: 'durk@gmail.com', password: '123456', name: 'Kanye West', seller: true, nickname: 'YE', description: 'One of the best emerging artists in 2021, thanks to his melodic voice and beautiful vocals. His has a wonderful devotion to his fans. He continuosly demonstrates it and we can see this through this merch drop dedicated exclusively to his beloved fans.', address: 'Girona')
photo_user6 = URI.open('https://cdn.mwallpapers.com/photos/celebrities/music/kanye-west-wallpaper-hd-android-iphone-desktop-hd-backgrounds-wallpapers-1080p-4khd-wallpapers-desktop-background-android-iphone-1080p-4k-w4nxy.jpg')
user6.photo.attach(io: File.open(photo_user6), filename: 'nes.jpg', content_type: 'image/jpg')
user7 = User.create(email: 'tony@gmail.com', password: '123456', name: 'Gue pequeno', seller: true, nickname: 'Gue', description: 'One of the best emerging artists in 2021, thanks to his melodic voice and beautiful vocals. His has a wonderful devotion to his fans. He continuosly demonstrates it and we can see this through this merch drop dedicated exclusively to his beloved fans.', address: 'Italy')
photo_user7 = URI.open('https://www.biografias.gratis/wp-content/uploads/Gue_Pequeno_Tatuaggi.jpg')
user7.photo.attach(io: File.open(photo_user7), filename: 'nes.jpg', content_type: 'image/jpg')
user8 = User.create(email: 'cent@gmail.com', password: '123456', name: 'Drake', seller: true, nickname: 'Champagne papi', description: 'One of the best emerging artists in 2021, thanks to his melodic voice and beautiful vocals. His has a wonderful devotion to his fans. He continuosly demonstrates it and we can see this through this merch drop dedicated exclusively to his beloved fans.', address: 'Girona')
photo_user8 = URI.open('https://wallpaperaccess.com/full/3517785.jpg')
user8.photo.attach(io: File.open(photo_user8), filename: 'nes.jpg', content_type: 'image/jpg')
user9 = User.create(email: 'ceciliog@gmail.com', password: '123456', name: 'J-Cole', seller: true, nickname: 'JC', description: 'One of the best emerging artists in 2021, thanks to his melodic voice and beautiful vocals. His has a wonderful devotion to his fans. He continuosly demonstrates it and we can see this through this merch drop dedicated exclusively to his beloved fans.', address: 'Italy')
photo_user9 = URI.open('https://static.onecms.io/wp-content/uploads/sites/6/2019/03/gettyimages-1026085768-2000.jpg')
user9.photo.attach(io: File.open(photo_user9), filename: 'nes.jpg', content_type: 'image/jpg')
user10 = User.create(email: 'rels@gmail.com', password: '123456', name: 'Rels B', seller: true, nickname: 'Skinny flak', description: 'One of the best emerging artists in 2021, thanks to his melodic voice and beautiful vocals. His has a wonderful devotion to his fans. He continuosly demonstrates it and we can see this through this merch drop dedicated exclusively to his beloved fans.', address: 'Girona')
photo_user10 = URI.open('https://yt3.ggpht.com/ytc/AKedOLROKOPedV_VvjRiE2upVYC1VGzxUNaGApOZegexjA=s900-c-k-c0x00ffffff-no-rj')
user10.photo.attach(io: File.open(photo_user10), filename: 'nes.jpg', content_type: 'image/jpg')
user11 = User.create(email: 'xxx@gmail.com', password: '123456', name: 'XXX-Tentacion', seller: true, nickname: 'XXX', description: 'One of the best emerging artists in 2021, thanks to his melodic voice and beautiful vocals. His has a wonderful devotion to his fans. He continuosly demonstrates it and we can see this through this merch drop dedicated exclusively to his beloved fans.', address: 'Girona')
photo_user11 = URI.open('https://images.hdqwalls.com/download/xxxtentacion-tz-2048x2048.jpg')
user11.photo.attach(io: File.open(photo_user11), filename: 'nes.jpg', content_type: 'image/jpg')

puts "Users created"

campaign1 = Campaign.create(user: user1, name:'Voglio Pippare', duration_days: 15, state: "active")
campaign2 = Campaign.create(user: user1, name:'Ya Tu Sabe', duration_days: 20, state: "active")
campaign3 = Campaign.create(user: user2, name:'Independence', duration_days: 10, state: "active")
campaign4 = Campaign.create(user: user2, name:'Winter Vibe', duration_days: 25, state: "active")
campaign5 = Campaign.create(user: user1, name:'New Year Merch', duration_days: 15, state: "inactive")
campaign6 = Campaign.create(user: user1, name:'2022 Tour Merch', duration_days: 20, state: "inactive")
campaign7 = Campaign.create(user: user2, name:'Album Merch Drop', duration_days: 10, state: "inactive")
campaign8 = Campaign.create(user: user2, name:'Artists Favourites Resale', duration_days: 25, state: "inactive")
campaign9 = Campaign.create(user: user5, name:'Summer Vibe II', duration_days: 15, state: "active")
campaign10 = Campaign.create(user: user5, name:'Long-sleeve Drop II', duration_days: 20, state: "active")
campaign11 = Campaign.create(user: user6, name:'Classic Tee II', duration_days: 10, state: "active")
campaign12 = Campaign.create(user: user6, name:'Winter Vibe II', duration_days: 25, state: "active")
campaign13 = Campaign.create(user: user7, name:'New Year Merch II', duration_days: 15, state: "active")
campaign14 = Campaign.create(user: user7, name:'2027 Tour', duration_days: 20, state: "active")
campaign15 = Campaign.create(user: user8, name:'Merch Drop Lion Tribe', duration_days: 10, state: "active")
campaign16 = Campaign.create(user: user8, name:'Artists Favourites', duration_days: 25, state: "active")
campaign17 = Campaign.create(user: user9, name:'Summer All Year', duration_days: 15, state: "active")
campaign18 = Campaign.create(user: user9, name:'Madame Drop', duration_days: 20, state: "active")
campaign19 = Campaign.create(user: user10, name:'Le Oui Oui Mon Ami', duration_days: 10, state: "active")
campaign20 = Campaign.create(user: user10, name:'Winter solstice', duration_days: 25, state: "active")
campaign21 = Campaign.create(user: user6, name:'Black-Out', duration_days: 15, state: "active")
campaign22 = Campaign.create(user: user5, name:'Zy-Ver', duration_days: 20, state: "inactive")
campaign23 = Campaign.create(user: user5, name:'AstroNomicaL', duration_days: 10, state: "active")
campaign24 = Campaign.create(user: user7, name:'Fan Homenage', duration_days: 25, state: "inactive")
campaign25 = Campaign.create(user: user7, name:'Indie World', duration_days: 15, state: "active")
campaign26 = Campaign.create(user: user8, name:'Landmark', duration_days: 20, state: "active")
campaign27 = Campaign.create(user: user9, name:'Classic Tee 2', duration_days: 10, state: "active")
campaign28 = Campaign.create(user: user10, name:'Winter 420 Blaze', duration_days: 25, state: "active")
campaign29 = Campaign.create(user: user9, name:'El Vagon', duration_days: 15, state: "active")
campaign30 = Campaign.create(user: user10, name:'Ya Tu Sabe', duration_days: 20, state: "inactive")
campaign31 = Campaign.create(user: user11, name:'Parce White X-Mas', duration_days: 10, state: "inactive")
campaign32 = Campaign.create(user: user11, name:'LAUGRA', duration_days: 25, state: "active")

puts "Campaigns created"

product1 = Product.create(user: user1, name:'White tee', price: 25, garment: 'T-shirt', color:'white', publish: true)
photo1 = URI.open('https://everpress.imgix.net/img/campaign/original/619cb705730bd7.14423200.png')
product1.photo.attach(io: File.open(photo1), filename: 'nes.png', content_type: 'image/png')

product2 = Product.create(user: user1, name:'Grey tee', price: 30, garment: 'T-shirt', color:'grey', publish: true)
photo2 = URI.open('https://everpress.imgix.net/img/campaign/original/619c4c44e79554.35840533.png')
product2.photo.attach(io: File.open(photo2), filename: 'nes.png', content_type: 'image/png')

product3 = Product.create(user: user1, name:'Black hoodie', price: 35, garment: 'hoodie', color:'black', publish: true)
photo3 = URI.open('https://everpress.imgix.net/img/campaign/original/6193f7663c0db8.34585728.png')
product3.photo.attach(io: File.open(photo3), filename: 'nes.png', content_type: 'image/png')

product4 = Product.create(user: user1, name:'Grey hoodiee', price: 40, garment: 'hoodie', color:'grey', publish: true)
photo4 = URI.open('https://everpress.imgix.net/img/campaign/original/6197b4fc1266a3.42972041.png')
product4.photo.attach(io: File.open(photo4), filename: 'nes.png', content_type: 'image/png')

product5 = Product.create(user: user1, name:'Grey long-sleeve', price: 28, garment: 'long-sleeve', color:'grey', publish: true)
photo5 = URI.open('https://everpress.imgix.net/img/campaign/original/619c3d3bf17461.11520242.png')
product5.photo.attach(io: File.open(photo5), filename: 'nes.png', content_type: 'image/png')

product6 = Product.create(user: user2, name:'White tee', price: 21, garment: 'T-shirt', color:'white', publish: true)
photo6 = URI.open('https://everpress.imgix.net/img/campaign/original/619bc3694e6e18.59902968.png')
product6.photo.attach(io: File.open(photo6), filename: 'nes.png', content_type: 'image/png')

product7 = Product.create(user: user2, name:'Grey tee', price: 19, garment: 'T-shirt', color:'grey', publish: true)
photo7 = URI.open('https://everpress.imgix.net/img/campaign/original/619c3d2919b0d0.64795800.png')
product7.photo.attach(io: File.open(photo7), filename: 'nes.png', content_type: 'image/png')

product8 = Product.create(user: user2, name:'Pink hoodie', price: 32, garment: 'hoodie', color:'pink', publish: true)
photo8 = URI.open('https://everpress.imgix.net/img/campaign/original/619aec88c75638.68713612.png')
product8.photo.attach(io: File.open(photo8), filename: 'nes.png', content_type: 'image/png')

product9 = Product.create(user: user2, name:'Grey hoodiee', price: 38, garment: 'hoodie', color:'grey', publish: true)
photo9 = URI.open('https://everpress.imgix.net/img/campaign/original/619aec75eed0b3.24444860.png')
product9.photo.attach(io: File.open(photo9), filename: 'nes.png', content_type: 'image/png')

product10 = Product.create(user: user2, name:'Grey long-sleeve', price: 23, garment: 'long-sleeve', color:'grey', publish: true)
photo10 = URI.open('https://everpress.imgix.net/img/campaign/original/61803819ab95c6.87146106.png')
product10.photo.attach(io: File.open(photo10), filename: 'nes.png', content_type: 'image/png')

product11 = Product.create(user: user5, name:'White tee', price: 25, garment: 'T-shirt', color:'white', publish: true)
photo11 = URI.open('https://everpress.imgix.net/img/campaign/original/619cb705730bd7.14423200.png')
product11.photo.attach(io: File.open(photo1), filename: 'nes.png', content_type: 'image/png')

product12 = Product.create(user: user5, name:'Grey tee', price: 30, garment: 'T-shirt', color:'grey', publish: true)
photo12 = URI.open('https://everpress.imgix.net/img/campaign/original/619c4c44e79554.35840533.png')
product12.photo.attach(io: File.open(photo2), filename: 'nes.png', content_type: 'image/png')

product13 = Product.create(user: user6, name:'Black hoodie', price: 35, garment: 'hoodie', color:'black', publish: true)
photo13 = URI.open('https://everpress.imgix.net/img/campaign/original/6193f7663c0db8.34585728.png')
product13.photo.attach(io: File.open(photo3), filename: 'nes.png', content_type: 'image/png')

product14 = Product.create(user: user6, name:'Grey hoodiee', price: 40, garment: 'hoodie', color:'grey', publish: true)
photo14 = URI.open('https://everpress.imgix.net/img/campaign/original/6197b4fc1266a3.42972041.png')
product14.photo.attach(io: File.open(photo4), filename: 'nes.png', content_type: 'image/png')

product15 = Product.create(user: user7, name:'Grey long-sleeve', price: 28, garment: 'long-sleeve', color:'grey', publish: true)
photo15 = URI.open('https://everpress.imgix.net/img/campaign/original/619c3d3bf17461.11520242.png')
product15.photo.attach(io: File.open(photo5), filename: 'nes.png', content_type: 'image/png')

product16 = Product.create(user: user7, name:'White tee', price: 21, garment: 'T-shirt', color:'white', publish: true)
photo16 = URI.open('https://everpress.imgix.net/img/campaign/original/619bc3694e6e18.59902968.png')
product16.photo.attach(io: File.open(photo6), filename: 'nes.png', content_type: 'image/png')

product17 = Product.create(user: user8, name:'Grey tee', price: 19, garment: 'T-shirt', color:'grey', publish: true)
photo17 = URI.open('https://everpress.imgix.net/img/campaign/original/619c3d2919b0d0.64795800.png')
product17.photo.attach(io: File.open(photo7), filename: 'nes.png', content_type: 'image/png')

product18 = Product.create(user: user8, name:'Pink hoodie', price: 32, garment: 'hoodie', color:'pink', publish: true)
photo18 = URI.open('https://everpress.imgix.net/img/campaign/original/619aec88c75638.68713612.png')
product18.photo.attach(io: File.open(photo8), filename: 'nes.png', content_type: 'image/png')

product19 = Product.create(user: user9, name:'Grey hoodiee', price: 38, garment: 'hoodie', color:'grey', publish: true)
photo19 = URI.open('https://everpress.imgix.net/img/campaign/original/619aec75eed0b3.24444860.png')
product19.photo.attach(io: File.open(photo9), filename: 'nes.png', content_type: 'image/png')

product20 = Product.create(user: user9, name:'Grey long-sleeve', price: 23, garment: 'long-sleeve', color:'grey', publish: true)
photo20 = URI.open('https://everpress.imgix.net/img/campaign/original/61803819ab95c6.87146106.png')
product20.photo.attach(io: File.open(photo10), filename: 'nes.png', content_type: 'image/png')

product21 = Product.create(user: user10, name:'Pink hoodie', price: 32, garment: 'hoodie', color:'pink', publish: true)
photo21 = URI.open('https://everpress.imgix.net/img/campaign/original/619aec88c75638.68713612.png')
product21.photo.attach(io: File.open(photo8), filename: 'nes.png', content_type: 'image/png')

product22 = Product.create(user: user10, name:'Grey hoodiee', price: 38, garment: 'hoodie', color:'grey', publish: true)
photo22 = URI.open('https://everpress.imgix.net/img/campaign/original/619aec75eed0b3.24444860.png')
product22.photo.attach(io: File.open(photo9), filename: 'nes.png', content_type: 'image/png')

product23 = Product.create(user: user11, name:'Grey long-sleeve', price: 23, garment: 'long-sleeve', color:'grey', publish: true)
photo23 = URI.open('https://everpress.imgix.net/img/campaign/original/61803819ab95c6.87146106.png')
product23.photo.attach(io: File.open(photo10), filename: 'nes.png', content_type: 'image/png')

product22 = Product.create(user: user10, name:'Grey hoodiee', price: 38, garment: 'hoodie', color:'grey', publish: true)
photo22 = URI.open('https://everpress.imgix.net/img/campaign/original/619aec75eed0b3.24444860.png')
product22.photo.attach(io: File.open(photo9), filename: 'nes.png', content_type: 'image/png')

puts "Products created"


campaignproduct1 = CampaignProduct.create(product: product1, campaign: campaign1)
campaignproduct2 = CampaignProduct.create(product: product2, campaign: campaign1)
campaignproduct3 = CampaignProduct.create(product: product3, campaign: campaign1)
campaignproduct4 = CampaignProduct.create(product: product4, campaign: campaign2)
campaignproduct5 = CampaignProduct.create(product: product5, campaign: campaign2)
campaignproduct6 = CampaignProduct.create(product: product6, campaign: campaign3)
campaignproduct7 = CampaignProduct.create(product: product7, campaign: campaign3)
campaignproduct8 = CampaignProduct.create(product: product8, campaign: campaign4)
campaignproduct9 = CampaignProduct.create(product: product9, campaign: campaign4)
campaignproduct10 = CampaignProduct.create(product: product10, campaign: campaign4)
campaignproduct11 = CampaignProduct.create(product: product1, campaign: campaign5)
campaignproduct12 = CampaignProduct.create(product: product2, campaign: campaign5)
campaignproduct13 = CampaignProduct.create(product: product3, campaign: campaign5)
campaignproduct14 = CampaignProduct.create(product: product4, campaign: campaign6)
campaignproduct15 = CampaignProduct.create(product: product5, campaign: campaign6)
campaignproduct16 = CampaignProduct.create(product: product6, campaign: campaign7)
campaignproduct17 = CampaignProduct.create(product: product7, campaign: campaign7)
campaignproduct18 = CampaignProduct.create(product: product8, campaign: campaign8)
campaignproduct19 = CampaignProduct.create(product: product9, campaign: campaign8)
campaignproduct20 = CampaignProduct.create(product: product10, campaign: campaign8)
campaignproduct21 = CampaignProduct.create(product: product11, campaign: campaign9)
campaignproduct22 = CampaignProduct.create(product: product12, campaign: campaign9)
campaignproduct23 = CampaignProduct.create(product: product13, campaign: campaign10)
campaignproduct24 = CampaignProduct.create(product: product14, campaign: campaign10)
campaignproduct25 = CampaignProduct.create(product: product15, campaign: campaign10)
campaignproduct26 = CampaignProduct.create(product: product16, campaign: campaign10)
campaignproduct27 = CampaignProduct.create(product: product17, campaign: campaign11)
campaignproduct28 = CampaignProduct.create(product: product18, campaign: campaign11)
campaignproduct29 = CampaignProduct.create(product: product19, campaign: campaign11)
campaignproduct30 = CampaignProduct.create(product: product20, campaign: campaign12)
campaignproduct31 = CampaignProduct.create(product: product21, campaign: campaign12)
campaignproduct32 = CampaignProduct.create(product: product22, campaign: campaign12)
campaignproduct33 = CampaignProduct.create(product: product11, campaign: campaign13)
campaignproduct34 = CampaignProduct.create(product: product12, campaign: campaign13)
campaignproduct35 = CampaignProduct.create(product: product13, campaign: campaign14)
campaignproduct36 = CampaignProduct.create(product: product14, campaign: campaign14)
campaignproduct37 = CampaignProduct.create(product: product15, campaign: campaign14)
campaignproduct38 = CampaignProduct.create(product: product16, campaign: campaign15)
campaignproduct39 = CampaignProduct.create(product: product17, campaign: campaign15)
campaignproduct40 = CampaignProduct.create(product: product18, campaign: campaign15)
campaignproduct41 = CampaignProduct.create(product: product11, campaign: campaign16)
campaignproduct42 = CampaignProduct.create(product: product12, campaign: campaign16)
campaignproduct43 = CampaignProduct.create(product: product13, campaign: campaign16)
campaignproduct44 = CampaignProduct.create(product: product14, campaign: campaign17)
campaignproduct45 = CampaignProduct.create(product: product15, campaign: campaign17)
campaignproduct46 = CampaignProduct.create(product: product16, campaign: campaign17)
campaignproduct47 = CampaignProduct.create(product: product17, campaign: campaign18)
campaignproduct48 = CampaignProduct.create(product: product18, campaign: campaign18)
campaignproduct49 = CampaignProduct.create(product: product19, campaign: campaign18)
campaignproduct50 = CampaignProduct.create(product: product20, campaign: campaign19)
campaignproduct51 = CampaignProduct.create(product: product21, campaign: campaign19)
campaignproduct52 = CampaignProduct.create(product: product22, campaign: campaign19)
campaignproduct53 = CampaignProduct.create(product: product11, campaign: campaign20)
campaignproduct54 = CampaignProduct.create(product: product12, campaign: campaign20)
campaignproduct55 = CampaignProduct.create(product: product13, campaign: campaign21)
campaignproduct56 = CampaignProduct.create(product: product14, campaign: campaign21)
campaignproduct57 = CampaignProduct.create(product: product15, campaign: campaign21)
campaignproduct58 = CampaignProduct.create(product: product16, campaign: campaign22)
campaignproduct59 = CampaignProduct.create(product: product17, campaign: campaign22)
campaignproduct60 = CampaignProduct.create(product: product18, campaign: campaign23)
campaignproduct61 = CampaignProduct.create(product: product21, campaign: campaign23)
campaignproduct62 = CampaignProduct.create(product: product22, campaign: campaign23)
campaignproduct63 = CampaignProduct.create(product: product11, campaign: campaign24)
campaignproduct64 = CampaignProduct.create(product: product12, campaign: campaign24)
campaignproduct65 = CampaignProduct.create(product: product13, campaign: campaign24)
campaignproduct66 = CampaignProduct.create(product: product14, campaign: campaign25)
campaignproduct67 = CampaignProduct.create(product: product15, campaign: campaign25)
campaignproduct68 = CampaignProduct.create(product: product16, campaign: campaign25)
campaignproduct69 = CampaignProduct.create(product: product17, campaign: campaign26)
campaignproduct70 = CampaignProduct.create(product: product18, campaign: campaign26)
campaignproduct71 = CampaignProduct.create(product: product21, campaign: campaign26)
campaignproduct72 = CampaignProduct.create(product: product22, campaign: campaign27)
campaignproduct73 = CampaignProduct.create(product: product11, campaign: campaign27)
campaignproduct74 = CampaignProduct.create(product: product12, campaign: campaign27)
campaignproduct75 = CampaignProduct.create(product: product13, campaign: campaign28)
campaignproduct76 = CampaignProduct.create(product: product14, campaign: campaign28)
campaignproduct77 = CampaignProduct.create(product: product15, campaign: campaign28)
campaignproduct78 = CampaignProduct.create(product: product16, campaign: campaign29)
campaignproduct79 = CampaignProduct.create(product: product17, campaign: campaign29)
campaignproduct80 = CampaignProduct.create(product: product18, campaign: campaign29)
campaignproduct81 = CampaignProduct.create(product: product21, campaign: campaign30)
campaignproduct82 = CampaignProduct.create(product: product22, campaign: campaign30)
campaignproduct83 = CampaignProduct.create(product: product11, campaign: campaign30)
campaignproduct84 = CampaignProduct.create(product: product12, campaign: campaign31)
campaignproduct85 = CampaignProduct.create(product: product13, campaign: campaign31)
campaignproduct86 = CampaignProduct.create(product: product14, campaign: campaign31)
campaignproduct87 = CampaignProduct.create(product: product15, campaign: campaign32)
campaignproduct88 = CampaignProduct.create(product: product16, campaign: campaign32)
campaignproduct89 = CampaignProduct.create(product: product17, campaign: campaign32)
campaignproduct90 = CampaignProduct.create(product: product18, campaign: campaign32)
puts "Campaign Products created"

order1 = Order.create(user: user3, status: "paid", total_price: 1500.34)
order2 = Order.create(user: user3, status: "paid", total_price: 502.25)
order3 = Order.create(user: user3, status: "pending")
order4 = Order.create(user: user4, status: "paid", total_price: 690.99)
order5 = Order.create(user: user4, status: "paid", total_price: 230.23)
order6 = Order.create(user: user4, status: "pending")
order7 = Order.create(user: user2, status: "paid", total_price: 340.12)
order8 = Order.create(user: user2, status: "pending")
order9 = Order.create(user: user1, status: "paid", total_price: 590.34)
order10 = Order.create(user: user1, status: "pending")

puts "Orders created"

orderitem1 = OrderItem.create(size: "L", quantity: 5, order: order1, status: "paid", campaign: campaignproduct1.campaign, product: campaignproduct1.product, value: 250.45)
orderitem2 = OrderItem.create(size: "S", quantity: 1, order: order1, status: "paid", campaign: campaignproduct2.campaign, product: campaignproduct2.product, value: 50.34)
orderitem3 = OrderItem.create(size: "M", quantity: 4, order: order1, status: "paid", campaign: campaignproduct3.campaign, product: campaignproduct3.product, value: 244.3)
orderitem4 = OrderItem.create(size: "L", quantity: 3, order: order1, status: "paid", campaign: campaignproduct4.campaign, product: campaignproduct4.product, value: 130)
orderitem5 = OrderItem.create(size: "S", quantity: 1, order: order2, status: "paid", campaign: campaignproduct5.campaign, product: campaignproduct5.product, value: 246.45)
orderitem6 = OrderItem.create(size: "M", quantity: 3, order: order2, status: "paid", campaign: campaignproduct6.campaign, product: campaignproduct6.product, value: 32.45)
orderitem7 = OrderItem.create(size: "L", quantity: 2, order: order2, status: "paid", campaign: campaignproduct7.campaign, product: campaignproduct7.product, value: 235.12)
orderitem8 = OrderItem.create(size: "S", quantity: 8, order: order2, status: "paid", campaign: campaignproduct8.campaign, product: campaignproduct8.product, value: 135.34)
orderitem9 = OrderItem.create(size: "L", quantity: 5, order: order3, campaign: campaignproduct9.campaign, product: campaignproduct9.product, value: 112.32)
orderitem10 = OrderItem.create(size: "S", quantity: 1, order: order3, campaign: campaignproduct10.campaign, product: campaignproduct10.product, value: 110.10)
orderitem11 = OrderItem.create(size: "M", quantity: 4, order: order3, campaign: campaignproduct3.campaign, product: campaignproduct3.product, value: 45.78)
orderitem12 = OrderItem.create(size: "L", quantity: 3, order: order4, status: "paid", campaign: campaignproduct4.campaign, product: campaignproduct4.product, value: 120)
orderitem13 = OrderItem.create(size: "S", quantity: 1, order: order4, status: "paid", campaign: campaignproduct5.campaign, product: campaignproduct5.product, value: 264)
orderitem14 = OrderItem.create(size: "M", quantity: 3, order: order4, status: "paid", campaign: campaignproduct9.campaign, product: campaignproduct9.product, value: 223.24)
orderitem15 = OrderItem.create(size: "L", quantity: 2, order: order4, status: "paid", campaign: campaignproduct7.campaign, product: campaignproduct7.product, value: 212.2)
orderitem16 = OrderItem.create(size: "S", quantity: 8, order: order5, status: "paid", campaign: campaignproduct8.campaign, product: campaignproduct8.product, value: 193.99)
orderitem17 = OrderItem.create(size: "L", quantity: 2, order: order5, status: "paid", campaign: campaignproduct7.campaign, product: campaignproduct7.product, value: 176.36)
orderitem18 = OrderItem.create(size: "S", quantity: 8, order: order5, status: "paid", campaign: campaignproduct10.campaign, product: campaignproduct10.product, value: 25)
orderitem19 = OrderItem.create(size: "L", quantity: 5, order: order6, campaign: campaignproduct1.campaign, product: campaignproduct1.product, value: 223.56)
orderitem20 = OrderItem.create(size: "S", quantity: 1, order: order6, campaign: campaignproduct2.campaign, product: campaignproduct2.product, value: 345.78)
orderitem21 = OrderItem.create(size: "M", quantity: 4, order: order6, campaign: campaignproduct3.campaign, product: campaignproduct3.product, value: 233.56)
orderitem22 = OrderItem.create(size: "L", quantity: 5, order: order7, status: "paid", campaign: campaignproduct9.campaign, product: campaignproduct9.product, value: 112.32)
orderitem23 = OrderItem.create(size: "S", quantity: 1, order: order7, status: "paid", campaign: campaignproduct10.campaign, product: campaignproduct10.product, value: 110.10)
orderitem24 = OrderItem.create(size: "M", quantity: 4, order: order7, status: "paid", campaign: campaignproduct3.campaign, product: campaignproduct3.product, value: 45.78)
orderitem25 = OrderItem.create(size: "L", quantity: 3, order: order8, campaign: campaignproduct4.campaign, product: campaignproduct4.product, value: 120)
orderitem26 = OrderItem.create(size: "S", quantity: 1, order: order8, campaign: campaignproduct5.campaign, product: campaignproduct5.product, value: 264)
orderitem27 = OrderItem.create(size: "M", quantity: 3, order: order8, campaign: campaignproduct9.campaign, product: campaignproduct9.product, value: 223.24)
orderitem28 = OrderItem.create(size: "L", quantity: 2, order: order8, campaign: campaignproduct7.campaign, product: campaignproduct7.product, value: 212.2)
orderitem29 = OrderItem.create(size: "S", quantity: 8, order: order9, status: "paid", campaign: campaignproduct8.campaign, product: campaignproduct8.product, value: 193.99)
orderitem30 = OrderItem.create(size: "L", quantity: 2, order: order9, status: "paid", campaign: campaignproduct7.campaign, product: campaignproduct7.product, value: 176.36)
orderitem31 = OrderItem.create(size: "S", quantity: 8, order: order9, status: "paid", campaign: campaignproduct10.campaign, product: campaignproduct10.product, value: 25)
orderitem32 = OrderItem.create(size: "L", quantity: 5, order: order10, campaign: campaignproduct1.campaign, product: campaignproduct1.product, value: 223.56)
orderitem33 = OrderItem.create(size: "S", quantity: 1, order: order10, campaign: campaignproduct2.campaign, product: campaignproduct2.product, value: 345.78)
orderitem34 = OrderItem.create(size: "M", quantity: 4, order: order10, campaign: campaignproduct3.campaign, product: campaignproduct3.product, value: 233.56)

puts "Order Items created"

payment1 = Payment.create(order: order1)
payment2 = Payment.create(order: order2)
payment3 = Payment.create(order: order4)
payment4 = Payment.create(order: order5)
payment5 = Payment.create(order: order7)
payment6 = Payment.create(order: order9)
